### ISSUE TITLE
Newlines is not converted

### ISSUE THREAD

**Issue by irvnriir** [phoihos/vscode-csv-to-md-table#2]
in CSV -- multi-line text is enclosed in quotes . in Markdown -- `<br />` .

**Comment by phoihos** [comment]
Could you upload the sample CSV contents that occur the issue?

**Comment by irvnriir** [comment]
```
"1
2","3"
"4","5"
```
Should support CR, LF and CR/LF newlines .

**Comment by phoihos** [comment]
I fixed this issue and released new version on [Marketplace](https://marketplace.visualstudio.com/items?itemName=phoihos.csv-to-md-table).
