### ISSUE TITLE
Convert CSV with first column with no name failed

### ISSUE THREAD

**Issue by broshet44** [phoihos/vscode-csv-to-md-table#3]
Hello

You plugin is very great and helpfull. But I have one problem. 
When I convert a tow column CSV with no name on the first columns it's failed :

`;NAME`
`A;1`
`B;2`

give me 

| ;NAME |
| ----- |
| A;1   |
| B;2   |
|       |

Is there anything I didn't see ?

PS : It's OK with more columns (3 or more)

**Comment by phoihos** [comment]
I'm tried to figure out this issue with below sample : 

![image](https://user-images.githubusercontent.com/19480673/192174776-5f9bd626-8388-466d-b148-294597a7ecdd.png)

But i could not find any issues.
I need more information related this issue.

Thank you for your reporting.

**Comment by phoihos** [comment]
This issue has been closed because there has been no response.
With only the information that is currently in the issue, i don't have enough information to take action.
Please reach out if you have or find the answers i need so that i can investigate further.
